experiment_name: open-DDVM
aml_config: a100x4.yaml
requirements_file: requirements_azure.txt
gpu_count: 4
code: 
cmd_line:
  python evaluate_diffusers_warprefine.py 
  --pipeline_path check_points/autoflow-CorrUnet/pipeline-305000 
  --normalize_range 
  --validation kitti sintel

input_data:
  - name: training_dataset
    blob_folder:
      container:
        subscription_id: 5c9e4789-4852-4ffe-8551-d682affcbd74
        resource_group: shared-rg
        storage_account: assharedw3data
        name: publicdatasets
      path: torchvision.datasets

output_data:
  - name: mnist_classifier
    blob_folder:
      container:
        subscription_id: 5c9e4789-4852-4ffe-8551-d682affcbd74
        resource_group: shared-rg
        storage_account: assharedw3data
        name: sampleoutputs
      path: mnist_classifier
